bw_recette_homepage:
    path:     /Recette
    defaults: { _controller: BWRecetteBundle:Recette:liste }

bw_recette_id:
    path:     /Recette/{idRecette}
    defaults: { _controller: BWRecetteBundle:Recette:detail }
    requirements:
        idRecette: \d+

bw_recette_creer_recette:
    path:     /creer/recette
    defaults: { _controller: BWRecetteBundle:Recette:creerRecette }

bw_recette_creer_ingredient:
    path:     /creer/ingredient
    defaults: { _controller: BWRecetteBundle:Recette:creerIngredient }

bw_recette_creation_ingredient:
    path:     /creation/ingredient
    defaults: { _controller: BWRecetteBundle:Recette:creationIngredient }

