bw_recette_homepage:
    path:     /Recette
    defaults: { _controller: BWRecetteBundle:Recette:liste }

bw_recette_id:
    path:     /Recette/{idRecette}
    defaults: { _controller: BWRecetteBundle:Recette:detail }
    requirements:
        idRecette: \d+

bw_creer_recette:
    path:     /Recette/Creer
    defaults: { _controller: BWRecetteBundle:Recette:creer }
