bw_recette:
    resource: "@BWRecetteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

home:
    path: /accueil
    defaults:
      _controller:
