<?php

namespace BW\UtilisateurBundle\Repository;

/**
 * UtilisateurRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
