<?php

namespace BW\RecetteBundle\Repository;

/**
 * ArchiveachatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveachatRepository extends \Doctrine\ORM\EntityRepository
{
}
