<?php

namespace BW\RecetteBundle\Repository;

/**
 * ArchiveplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveplanRepository extends \Doctrine\ORM\EntityRepository
{
}
