<?php

namespace BW\RecetteBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{

	public function getListeRecette(){
		$qb = $this->createQueryBuilder('r')
			->leftjoin('r.images', 'im')
			->leftjoin('r.utilisateur', 'u')
			->addSelect('im');

		return $listeRecette = $qb->getQuery()->getResult();
	}

	public function getDetailsRecette($id){
		$qb = $this->createQueryBuilder('r')
			->leftjoin('r.images', 'im')
			->leftjoin('r.utilisateur', 'u')
			->leftjoin('r.quantites', 'q')
			->leftjoin('q.ingredient', 'in')
			->addSelect('im')
			->addSelect('q')
			->addSelect('in');

			//Etape

		return $listeRecette = $qb->getQuery()->getResult();
	}
}
