<?php

namespace BW\RecetteBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{

	public function getListeRecette(){
		$qb = $this->createQueryBuilder('r')
			->leftjoin('r.images', 'im')
			->leftjoin('r.utilisateur', 'u')
			->addSelect('im');

		return $qb->getQuery()->getResult();
	}

	public function getDetailRecette($id){
		$qb = $this->createQueryBuilder('r')
			->leftjoin('r.images', 'im')
			->leftjoin('r.utilisateur', 'u')
			->leftjoin('r.etapes', 'e')
			->leftjoin('r.quantites', 'q')
			->leftjoin('q.ingredient', 'ing')
			->addSelect('im')
			->addSelect('q')
			->addSelect('e')
			->addSelect('ing')
			->andWhere('r.id = :id')
            ->setParameter('id', $id);

			//Manque Etape mais zappé car pas le temps

		return $qb->getQuery()->getOneOrNullResult();
	}
}
