<?php

namespace BW\RecetteBundle\Repository;

/**
 * SuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuitRepository extends \Doctrine\ORM\EntityRepository
{
}
