BW\RecetteBundle\Entity\Appartient:
    type: entity
    table: appartient
    indexes:
        FK_appartient_idcat:
            columns:
                - idcat
    id:
        idingredient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
        idcat:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    lifecycleCallbacks: {  }
