BW\RecetteBundle\Entity\Archiveachat:
    type: entity
    table: archiveachat
    indexes:
        FK_archiveachat_idingredient:
            columns:
                - idingredient
    uniqueConstraints:
        idarchivplan:
            columns:
                - idarchivplan
    id:
        idarchivplan:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
        idingredient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        datea:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
