BW\RecetteBundle\Entity\Categorie:
    type: entity
    table: categorie
    indexes:
        idcat:
            columns:
                - idcat
    uniqueConstraints:
        nomc:
            columns:
                - nomc
        idcat_2:
            columns:
                - idcat
        IndexCat:
            columns:
                - idcat
        idcat_3:
            columns:
                - idcat
    id:
        idcat:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomc:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        descriptionc:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
