BW\RecetteBundle\Entity\Etape:
    type: entity
    table: etape
    indexes:
        FK_etape_idrecette:
            columns:
                - idrecette
        idetape:
            columns:
                - idetape
    id:
        idetape:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descriptione:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        dureee:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
        idrecette:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
