BW\RecetteBundle\Entity\Ingredient:
    type: entity
    table: ingredient
    indexes:
        FK_ingredient_login:
            columns:
                - login
        idingredient:
            columns:
                - idingredient
    uniqueConstraints:
        idingredient_2:
            columns:
                - idingredient
        idingredient_3:
            columns:
                - idingredient
    id:
        idingredient:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomi:
            type: string
            nullable: true
            length: '20'
            options:
                fixed: false
        dispodefaut:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        typemesure:
            type: string
            nullable: false
            length: '10'
            options:
                fixed: false
        popularite:
            type: integer
            nullable: true
            options:
                unsigned: false
        sansgluten:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        vegetarienne:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        pescetarien:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        login:
            type: string
            nullable: true
            length: '25'
            options:
                fixed: false
    lifecycleCallbacks: {  }
