BW\RecetteBundle\Entity\Recette:
    type: entity
    table: recette
    indexes:
        FK_recette_id:
            columns:
                - id
        idrecette_2:
            columns:
                - idrecette
    uniqueConstraints:
        idrecette:
            columns:
                - idrecette
        idrecette_3:
            columns:
                - idrecette
    id:
        idrecette:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        difficulte:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        prix:
            type: integer
            nullable: false
            options:
                unsigned: false
        nombrepersonne:
            type: integer
            nullable: false
            options:
                unsigned: false
        duree:
            type: integer
            nullable: false
            options:
                unsigned: false
        nom:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        calories:
            type: integer
            nullable: true
            options:
                unsigned: false
        glucide:
            type: integer
            nullable: true
            options:
                unsigned: false
        lipide:
            type: integer
            nullable: true
            options:
                unsigned: false
        proteines:
            type: integer
            nullable: true
            options:
                unsigned: false
        selmineraux:
            type: integer
            nullable: true
            options:
                unsigned: false
        id:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
