BW\RecetteBundle\Entity\Regime:
    type: entity
    table: regime
    indexes:
        idregime:
            columns:
                - idregime
    uniqueConstraints:
        nomr:
            columns:
                - nomr
        idregime_2:
            columns:
                - idregime
    id:
        idregime:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomr:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        descriptionr:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
