BW\RecetteBundle\Entity\Utilisateur:
    type: entity
    table: utilisateur
    id:
        login:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        adressemail:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        motdepasse:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        nom:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
    lifecycleCallbacks: {  }
