BW\RecetteBundle\Entity\Video:
    type: entity
    table: video
    indexes:
        FK_video_idrecette:
            columns:
                - idrecette
        idvideo:
            columns:
                - idvideo
    uniqueConstraints:
        idvideo_2:
            columns:
                - idvideo
    id:
        idvideo:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lienv:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        idrecette:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
