bw_utilisateur_homepage:
    path:     /
    defaults: { _controller: BWUtilisateurBundle:Utilisateur:index }

bw_admin_homepage:
    path:     /admin
    defaults: { _controller: BWUtilisateurBundle:Admin:index }