bw_utilisateur_homepage:
    path:     /
    defaults: { _controller: BWUtilisateurBundle:Utilisateur:index }

bw_utilisateur_antoine:
    path:     /antoine
    defaults: { _controller: BWUtilisateurBundle:Utilisateur:login }