bw_utilisateur_homepage:
    path:     /
    defaults: { _controller: BWUtilisateurBundle:Utilisateur:index }

bw_admin_homepage:
    path:     /admin
    defaults: { _controller: BWUtilisateurBundle:Admin:index }

bw_admin_tableau_uti:
    path:     /admin/tableau/utilisateur
    defaults: { _controller: BWUtilisateurBundle:Admin:tableauUtilisateur }

bw_admin_modifier_uti:
    path:     /admin/modifier/utilisateur/{id}
    defaults: { _controller: BWUtilisateurBundle:Admin:modifierUtilisateur }
    requirements:
        id:   \d

bw_admin_modification_uti:
    path:     /admin/modification/utilisateur
    defaults: { _controller: BWUtilisateurBundle:Admin:modificationUtilisateur }

bw_admin_suppression_uti:
    path:     /admin/suppression/utilisateur
    defaults: { _controller: BWUtilisateurBundle:Admin:suppressionUtilisateur }

bw_admin_tableau_ingredient:
    path:     /admin/tableau/ingredient
    defaults: { _controller: BWUtilisateurBundle:Admin:tableauIngredient }

bw_admin_suppression_ingredient:
    path:     /admin/suppression/ingredient
    defaults: { _controller: BWUtilisateurBundle:Admin:suppressionIngredient }

bw_admin_tableau_recette:
    path:     /admin/tableau/recette
    defaults: { _controller: BWUtilisateurBundle:Admin:tableauRecette }

bw_admin_suppression_recette:
    path:     /admin/suppression/recette
    defaults: { _controller: BWUtilisateurBundle:Admin:suppressionRecette }